services:
# build the mongodb server to store the document of the products
  product_db:
    image: mongo:6.0
    container_name: product_db
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - product_data:/data/db

# build the minio server as s3 storage
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

# init the images bucket and set it's as public :)
  minio_init:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
        sleep 5;
        mc alias set local http://minio:9000 admin admin123;
        mc mb local/images;
        mc anonymous set download local/images;
        echo '✅ Bucket \"images\" created and made public';
      "

volumes:
  product_data:
  minio_data:
